import Foundation

/// A packed 8-bit-per-channel colour. Deliberately not `UIColor`/`SwiftUI.Color`
/// so that `SlateTheme` stays dependency-free and testable on any platform.
public struct RGB: Hashable, Sendable, Codable {
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8

    public init(r: UInt8, g: UInt8, b: UInt8) {
        self.r = r
        self.g = g
        self.b = b
    }

    /// Parses `#rrggbb` or `rrggbb`. Returns nil for anything else — themes are
    /// user-editable, so this needs to fail rather than trap.
    public init?(hex: String) {
        var text = Substring(hex)
        if text.hasPrefix("#") { text = text.dropFirst() }
        guard text.count == 6, let value = UInt32(text, radix: 16) else { return nil }
        self.init(
            r: UInt8((value >> 16) & 0xFF),
            g: UInt8((value >> 8) & 0xFF),
            b: UInt8(value & 0xFF)
        )
    }

    public var hex: String {
        String(format: "#%02x%02x%02x", r, g, b)
    }

    /// Linear 0...1 components, which is what both Metal and SwiftUI want.
    public var components: (Float, Float, Float) {
        (Float(r) / 255, Float(g) / 255, Float(b) / 255)
    }

    /// Relative luminance (WCAG). Used to decide whether a theme reads as light
    /// or dark when a theme file doesn't say.
    public var luminance: Double {
        func channel(_ raw: UInt8) -> Double {
            let value = Double(raw) / 255
            return value <= 0.03928 ? value / 12.92 : pow((value + 0.055) / 1.055, 2.4)
        }
        return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)
    }
}

/// A terminal colour scheme: the 16 ANSI slots plus the handful of UI colours a
/// terminal needs. Matches the shape of a Ghostty/iTerm2 theme file so importing
/// one is a parse, not a translation.
public struct Theme: Identifiable, Hashable, Sendable, Codable {
    public var name: String
    public var background: RGB
    public var foreground: RGB
    public var cursor: RGB
    public var selectionBackground: RGB
    public var selectionForeground: RGB?

    /// ANSI 0-15. Slots 16-255 are generated by `paletteEntry(_:)`, which
    /// follows the standard xterm cube + greyscale ramp.
    public var ansi: [RGB]

    public var id: String { name }

    public init(
        name: String,
        background: RGB,
        foreground: RGB,
        cursor: RGB,
        selectionBackground: RGB,
        selectionForeground: RGB? = nil,
        ansi: [RGB]
    ) {
        precondition(ansi.count == 16, "a theme must define exactly 16 ANSI colours")
        self.name = name
        self.background = background
        self.foreground = foreground
        self.cursor = cursor
        self.selectionBackground = selectionBackground
        self.selectionForeground = selectionForeground
        self.ansi = ansi
    }

    public var isDark: Bool { background.luminance < 0.5 }

    /// The full 256-colour palette, with 16-231 as the 6x6x6 cube and 232-255 as
    /// the greyscale ramp. libghostty hands us palette indices for indexed
    /// colours, so we need all 256.
    public func paletteEntry(_ index: UInt8) -> RGB {
        switch index {
        case 0..<16:
            return ansi[Int(index)]
        case 16..<232:
            let offset = Int(index) - 16
            let levels: [UInt8] = [0, 95, 135, 175, 215, 255]
            return RGB(
                r: levels[(offset / 36) % 6],
                g: levels[(offset / 6) % 6],
                b: levels[offset % 6]
            )
        default:
            let level = UInt8(8 + (Int(index) - 232) * 10)
            return RGB(r: level, g: level, b: level)
        }
    }

    /// The 256-entry palette flattened once, for handing to libghostty's
    /// `GHOSTTY_TERMINAL_OPT_COLOR_PALETTE`.
    public var palette256: [RGB] {
        (0...255).map { paletteEntry(UInt8($0)) }
    }
}

extension Theme {
    /// Convenience for the built-in table below: 16 hex strings in ANSI order.
    /// Traps on a malformed literal, which is what you want for compile-time
    /// constants — a typo in a built-in theme is a bug, not a runtime condition.
    static func make(
        _ name: String,
        background: String,
        foreground: String,
        cursor: String,
        selection: String,
        ansi: [String]
    ) -> Theme {
        func parse(_ hex: String) -> RGB {
            guard let color = RGB(hex: hex) else {
                preconditionFailure("built-in theme \(name) has an invalid colour: \(hex)")
            }
            return color
        }
        return Theme(
            name: name,
            background: parse(background),
            foreground: parse(foreground),
            cursor: parse(cursor),
            selectionBackground: parse(selection),
            ansi: ansi.map(parse)
        )
    }
}
